### PR TITLE
Convert to proper YAML library

### PR DESCRIPTION
**Pull request by hvr**

### CODE REVIEW

**Comment by osa1** [comment]
So, standard compliance is good, but in this case we care more about stack compatibility than standard compliance, and stack currently uses `yaml`.

That said, as a user I won't complain unless stack accepts some stack.yaml files that stack2cabal rejects.

**Comment by edsko** [comment]
@hvr are you aware of any `stack.yaml` in the wild that cannot be parsed by the standards compliant parser?

**Comment by hvr** [comment]
I'm not aware of any... and I'm not sure how I can get my hands on a large enough quantity of `stack.yaml` files; fwiw, https://github.com/erikd/jenga is also using HsYAML for parsing stack.yaml files... and I haven't heard any complaints yet.

**Comment by edsko** [comment]
Ok.

**Pull request merged**
